name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ext-ctype, ext-dom, ext-json, ext-libxml, ext-mbstring, ext-phar, ext-tokenizer, ext-xml, ext-xmlwriter

    - name: Check PHP Version
      run: php -v

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Execute tests
      run: ./vendor/bin/phpunit --stop-on-failure

    - name: Run PHPStan
      run: ./vendor/bin/phpstan --error-format=github
